### ISSUE TITLE
Add removal of exited guild members from Giveaway

### ISSUE THREAD

**Issue by megoRU** [megoRU/GiveawayDiscordBot#22]
EN:
In theory, if a person wins who is not in the drawing, it will be difficult to contact him.
Perhaps it is worth making a choice in Slash whether to exclude such immediately. (load on the bot)

(Best practices)
You can do more, when choosing a winner, check the participant in the guild. If it is not there, then notify with a message with two buttons. Yes, Reroll. !Make a notification that the Reroll will be standard when created (number of participants in the drawing)

_______________________________

RU:
По идее, если человек выиграет которого нет в розыгрыше, с ним будет сложно связаться.
Возможно стоит сделать выбор в Slash исключать ли таких сразу. (нагрузка на бота)

(Best practices)
Можно сделать ещё, при выборе победителя проверять участника в гильдии. Если его нет тогда уведомлять сообщением с двумя кнопками. Да, Reroll. !Сделать уведомление что Reroll будет стандартным при создании (количество участников при розыгрыше)

**Comment by PegasusNZ** [comment]
Maybe a lucky loser as a spare! I often get players not wanting the giveaway a spare member in the draw would be handy?

**Comment by megoRU** [comment]
> Maybe a lucky loser as a spare! I often get players not wanting the giveaway a spare member in the draw would be handy?

I didn't quite understand what you meant

**Comment by megoRU** [comment]
I think this issue #59 close this case

**Comment by megoRU** [comment]
Discord bot intents need for this.
